site_name: MetSCORE
site_description: Python implementation of MetSCORE
site_url: https://omilletlab.github.io/metscore/

repo_url: https://github.com/omilletlab/metscore
repo_name: omilletlab/metscore
edit_uri: ""

theme:
  name: mkdocs
  navigation_depth: 3

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            heading_level: 3

nav:
  - Home: index.md
  - Web interface: web-app.md
  - API Reference: api.md
